server:
  port: 9092
  
spring:
  application:
    name: user-service
    
    
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userservicedb
      
eureka:
  instance:
    hostname: localhost

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              
jwtSecret:
    jwtSecretKey
jwtExpirationMs:
  86400000
